### ISSUE TITLE
pip install fails 

### ISSUE THREAD

**Issue by ksteward** [randyridgley/cdk-datalake-constructs#21]
This is an interesting project that I'd like to use.  I'm a pythonista so I was hoping to do the pip install.  However it fails to find the python module (in PyPi?):

`$ pip install cdk-datalake-constructs.cdk-datalake-constructs`

Any suggestions?

**Comment by randyridgley** [comment]
I need to update the docs. Originally I had it as the library above and now it's just:
pip3 install cdk-datalake-constructs the pypi page is listed here https://pypi.org/project/cdk-datalake-constructs/

Thanks for the interest and would love any feedback.

**Comment by randyridgley** [comment]
Update docs to reflect correct name for pypi install
